[package]
name = "avd-menu"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Gerenciador de emuladores Android (Device Manager + SDK Manager) sem Java"
default-run = "avd-menu"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
avdcore = { path = "../crates/core" }
serde_json = "1"
tauri = { version = "2", features = [] }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
tauri-plugin-single-instance = "2"
