[workspace]
resolver = "2"
members = ["crates/core", "src-tauri", "xtask"]

[workspace.package]
version = "1.0.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/thiagotognoli/avd-menu"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
